// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mcamfosfqcoqepruetqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYW1mb3NmcWNvcWVwcnVldHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODI3MDAsImV4cCI6MjA3NDg1ODcwMH0.oi8GGmV6SAFYCT2Dx_mPVsmNgKQxbkKXSO6K8zXpZmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);